# print('Hello world')
# print('Hello')
# name = input('what is your name ? ')
# tariq = input('qani tarekan eq duq? ')
# print ('my name is ', name, 'es',tariq'tarekan em')
#print ('es',tariq,'tarekan em')
# usum =input('vortex eq sovorum? ')
# darnal=input('inch eq cankanum darnal? ')
# print('es sovorum em',usum, 'uzum em darnal' ,darnal)
born=input('when you was born? ')
print('you are',2020-int(born),('years old'))